### ISSUE TITLE
Prism?

### ISSUE THREAD

**Issue by tomByrer** [johnzanussi/astro-mdx-code-blocks#1]
Looks like we also have to:
```js
import { Prism } from '@astrojs/prism`
```
But aside of the `CodeBlock.astro` example, it is not documented anywhere.  Your Stackbliz does not have `@astrojs/prism` listed in `package.json` either.... is Prism automatically included in all Astro installs?

Thanks for building this, will likely use with my blog!

**Comment by johnzanussi** [comment]
You're right. I've gone ahead and updated the demo to include the `@astrojs/prism` package. I'm unsure why the demo worked without it being installed.

However, the beauty of using your own component is you can use any method you'd like for syntax highlighting, be it Prism, Shiki, or some other third-party library.

I've also added a note to the [README](https://github.com/johnzanussi/astro-mdx-code-blocks#example-component) to include that.

> This example uses Astro's [Prism component](https://docs.astro.build/en/reference/api-reference/#prism-) for syntax highlighting. However, you can use any library you'd like, as the component has access to the raw code string.

Please do let me know your experience using it on your blog. Cheers.
