### ISSUE TITLE
Extra prop CodeBlockProps type: 

### ISSUE THREAD

**Issue by mgcrea** [johnzanussi/astro-mdx-code-blocks#2]
Looks like you left some kind of typo in the `CodeBlockProps` type (extraneous foo prop):

https://github.com/johnzanussi/astro-mdx-code-blocks/blob/01dd32f93ede2456c6c27e1df3b3edaaf7626e2c/src/index.ts#L8

**Comment by johnzanussi** [comment]
Thanks for pointing this out. I will remove in the next update.

**Comment by johnzanussi** [comment]
This has been fixed in the latest version 0.0.4.
