### ISSUE TITLE
Line counts and indentations break on Astro v4

### ISSUE THREAD

**Issue by YonicDev** [johnzanussi/astro-mdx-code-blocks#3]
When upgrading from Astro v3 to Astro v4, line indentations made with spaces do not work properly and the integration considers it to be part of the same line as the previous one, disregarding line breaks.

Before upgrading to v4.0 (correctly rendered):
![imagen](https://github.com/johnzanussi/astro-mdx-code-blocks/assets/9784263/2399135a-b717-4d46-8006-0b69dd454a3f)

After upgrading to v4.0 (incorrectly rendered):
![imagen](https://github.com/johnzanussi/astro-mdx-code-blocks/assets/9784263/fcfeb0e4-41b6-4551-8023-4d4509cb7e1a)

**Comment by johnzanussi** [comment]
Closing because upstream changes fixed the issue. Thanks again @YonicDev.
